version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "19:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge" # Used by Kodiak to work out what to automerge
